/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CompilerWorks;

import java.io.BufferedReader;
import java.io.InputStreamReader;

public class NQueens {
	private int getNumberOfQueens() {
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
		int number = -1;
		
    	System.out.print("Enter number of queens ('N'): ");
    	try {
    		number = Integer.parseInt(br.readLine());
    		if (number < 0) {
    			throw new Exception();
    		}
    	}
    	catch (Exception e) {
    		System.out.println("Please enter valid input (1....N). Program will exit now.");
    		System.exit(0);
    	}
    	return number;
	};
	
	public static void main(String[] args) {
		NQueens nqueens = new NQueens();
    	int numberOfQueens = nqueens.getNumberOfQueens();
    	char[][] chessBoard = new char [numberOfQueens][numberOfQueens];
    	nqueens.initializeChessBoard(chessBoard);
    	nqueens.printChessBoard(chessBoard);
    }
	
	private void printChessBoard(char chessBoard[][]) {
		for (int i = 0; i < chessBoard.length; i++) {
			for (int j = 0; j < chessBoard[i].length; j++) {
				System.out.print(chessBoard[i][j] + " ");
			}
			System.out.println();
		}
	};
	
	private void initializeChessBoard(char chessBoard[][]) {
		for (int i = 0; i < chessBoard.length; i++) {
			for (int j = 0; j < chessBoard[i].length; j++) {
				chessBoard[i][j] = '_';
			}
		}
	}
}