/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CompilerWorks;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
   /* @Test public void testAppHasAGreeting() {
        NQueens classUnderTest = new NQueens();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    */
}
